### ISSUE TITLE
Machines without latest WUA Agent Version check not handling Win10 versions correctly

### ISSUE THREAD

**Issue by ColinBlackman** [Skatterbrainz/CMHealthCheck#10]
The first select in MachineswithoutlatestWindowsUpdateAgentVersion returns Windows 10 machines. ops.Version0, and LatestWUAVersion need to be treated like software versions instead of integers. 

A quick and dirty workaround is to replace 
"where ops.Version0 &lt; '6.2' and uss.LastWUAVersion &lt; '7.6.7600.256'"
in the XML file with
where ops.Version0 &lt; '6.2' and ops.Version 0 NOT LIKE '10.0%' and uss.LastWUAVersion &lt; '7.6.7600.256'

**Comment by Skatterbrainz** [comment]
Thank you!  I'll be working on this very soon.

**Comment by Skatterbrainz** [comment]
Modified lines 1806 to 1847 to exclude Windows 10 resources from the result data set.
