### ISSUE TITLE
Creates and Empty Folder and Quits

### ISSUE THREAD

**Issue by hang10z** [Skatterbrainz/CMHealthCheck#62]
I am running Get-CMHealthCheck -SMSProvider "Servername"  or even just Get-CMHealthCheck (I have tried running the command from Primary Site servers, CAS and workstations.

The script gets to "Gathering site and server information" and then quits and creates an empty output folder under my documents.

**To Reproduce**
Run Get-CMHealthCheck with or without args

**Expected behavior**
Collect SCCM Data

**Screenshots**
![image](https://user-images.githubusercontent.com/6350443/83530963-6b57a600-a4ba-11ea-890a-080595a6f477.png)

I don't see a log file or anything to help troubleshoot.  Was hoping to use this script to document and troubleshoot a very large SCCM environment.

**Comment by hang10z** [comment]
Thanks for the help! :)

**Comment by Skatterbrainz** [comment]
Sorry for the delay in getting to this, but I'm looking into this now.

**Comment by Skatterbrainz** [comment]
Can you confirm what version of the module you are using?  This issue should've been fixed in 1.0.25. Just making sure if I still need to dig into that.

**Comment by hang10z** [comment]
It was version 1.0.25.  I'll try again this upcoming week in a different environment to see if I get the same results.

**Comment by Skatterbrainz** [comment]
Thank you for being patient, I'm hoping to get this resolved asap.  Disregard previous msg (today).  I see you're using the Get-CMHealthCheck function not the combined function that gathers and exports in one process.

**Comment by Skatterbrainz** [comment]
Should be fixed in 1.0.26 - this appears to be due to not using the -Overwrite parameter.  I've added that into the warning text.
