### ISSUE TITLE
Issue when Running Script

### ISSUE THREAD

**Issue by Robinson89120** [Skatterbrainz/CMHealthCheck#67]
**Describe the bug**

Unable to generate the XML files when running get-cmhealthcheck
Data collection process completed. Total Runtime: 00:00:03 (hh:mm:ss)
Unable to copy contents of Log file - Refer to Attached PNG
![AFxQbxuXTf](https://github.com/Skatterbrainz/CMHealthCheck/assets/78626091/4177c4c5-d8a8-49f6-916c-40e504d2d952)

**To Reproduce**
1. Launch powershell
2. Import-Module CMHealthChek
3. Get-CMHealthCheck -OutputFolder "C:\Reports" -Overwrite

**Site Info (please complete the following information):**
 - Host OS Version: Windows Server 2019
 - SCCM Version: 2211
 - SQL Version 2014
 - Word Version: N.A
 
 **Additional context**
No issue with SQL Rights

**Comment by Skatterbrainz** [comment]
The error message appears to indicate a SQL connection failure. Make sure you run the script from a user session that has required permissions into the SQL instance and database. Double check the instance and database names also.

**Comment by Skatterbrainz** [comment]
Closing issue due to lack of response/activity
