### ISSUE TITLE
Last SQL Backup does not return the last backup date.

### ISSUE THREAD

**Issue by ColinBlackman** [Skatterbrainz/CMHealthCheck#9]
Query is returning the first backup it finds within the 7 day windows, adding "Order BY s.backup_finish_date desc" to the end of the query allows it to return the most recent completed backup within the last 7 days.

**Comment by Skatterbrainz** [comment]
Thank you for the suggested fix!

**Comment by Skatterbrainz** [comment]
Modified line 428 in cmhealthcheck.xml for 1.0.4 branch release

**Comment by Skatterbrainz** [comment]
Modified line 999 in cmhealthcheck.xml for 1.0.4 branch release
